project:
  type: website

website:
  title: "CBIT200 Programación Geoespacial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: CursoProgamacion/_book/index.Rmd
        text: Libro del curso

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



