---
title: "Tarea03 - Reproducibilidad"
author: "Horacio Samaniego"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Para realizar esta tarea, ustedes deberán tomar la base de datos entregada en este repositorio. La base de datos se llama "Protected Areas" y la pueden encontrar como Protected_Areas.rds
Como vimos en clase, .rds es un tipo de archivos nativo de R que permite guardar cualquier tipo de información, ya sea imágenes, archivos escritos, tablas, etc. En este caso este archivo corresponde a un data frame.

Ustedes deberán leer el data frame y revisar la información que contine. **Protected_Areas.rds** posee información sobre todas las areas protegidas del país y se encuentra dividida en 10 columnas o variables.


### Actividades

1. Generar una tabla resumen de la superficie comprendida por áreas protegidas terrestres, considerando regiones por separado y cada tipo de area protegida por separado.

2. Generar una tabla resumen del número de áreas protegidas por cada tipo, considerando solo la región de Los lagos.

3. Indicar con un inline code cuál es el área protegida terrestre que posee la mayor superficie en la región de Los Lagos.


### Evaluación

Esta tarea deberá ser resuelta en un archivo .Rmd que deberán subir a este mismo repositorio haciendo commit y push desde su computador.
En el documento .Rmd no deben poner su nombre.
Podrán hacer cuantos cambios quieran, pero la última versión deberá estar subida el día lunes 16 a las 11:59 PM.

Cada actividad valdrá dos puntos y contarán con un punto base para una nota de 7.
